volumes:
  db-data:

services:
  nginx:
    image: ghcr.io/damiankocher/local-convention-dashboard-nginx:main
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server.crt:/etc/ssl/crt/server.crt
      - ./server.key:/etc/ssl/crt/server.key
    restart: always

  server:
    image: ghcr.io/damiankocher/local-convention-dashboard-server:main
    env_file:
      - .env
    environment:
      PGHOST: postgres
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: always

  database:
    image: postgres:16-alpine
    hostname: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: dsa
      POSTGRES_DB: convention
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
