services:
  nginx:
    image: ghcr.io/damiankocher/local-convention-dashboard-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server.crt:/etc/ssl/crt/server.crt
      - ./server.key:/etc/ssl/crt/server.key
    restart: always
